/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Modelos.Cad_Reuniao;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Modelos.SalaR_Comum;

/**
 *
 * @author junio
 */
public class Formulario_CadR_Coordenador extends javax.swing.JFrame {
     
     Cad_Reuniao crc = new Cad_Reuniao();//Instanciando objeto
     
     Relatorio_Presença_Reunioes visualizar;//Objeto Nulo
     
     ArrayList<Cad_Reuniao> listaR = new ArrayList<>();// criando ArrayList
     
     Relatorio_Cad_Reuniao_Coordenador rcr;//Objeto Nulo
     
    /**
     * Creates new form Formulario_CadR_Coordenador
     */
    public Formulario_CadR_Coordenador() {
        initComponents();
        
        this.setLocationRelativeTo(null);// Centraliza a tela
    }
    
    //Percorre o ArrayList e retorna o toString 
    public String percorrendoObjeto(){
        
        String informacao = "";
        
        for(Cad_Reuniao cad : listaR){
            informacao += cad;
        }
        
        return informacao;
    }
    
    //visualiza uma janela com toString se caso o rcr for nulo
    public void visualizarRelatorio(){
        
        if (rcr == null) {
            rcr = new Relatorio_Cad_Reuniao_Coordenador();
            rcr.setVisible(true);
            rcr.exibirRelatorio(percorrendoObjeto());
        }
    }
    
    //Limpa os dados
    public void limparDados(){
        
        txtPauta.setText("");
        txtAta.setText("");
        txtDia.setText("");
        txtHora_Inicio.setText("");
        txtHora_Fim.setText("");
        txtPresenca.setText("");
        txtTema.setText("");
        txtProprietario.setText("");
        txtnPessoas.setText("");
        txtSugestao.setText("");
        txtRecebeSala.setText("");
        txtCadSala.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtPauta = new javax.swing.JTextField();
        txtAta = new javax.swing.JTextField();
        txtTema = new javax.swing.JTextField();
        txtnPessoas = new javax.swing.JTextField();
        txtProprietario = new javax.swing.JTextField();
        txtPresenca = new javax.swing.JTextField();
        txtDia = new javax.swing.JTextField();
        txtHora_Inicio = new javax.swing.JTextField();
        txtHora_Fim = new javax.swing.JTextField();
        txtSugestao = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_Reuniao_Coordenador = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        btnIncluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnVisualizarRelatorio = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        btnVisualizarReunioes = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtCadSala = new javax.swing.JTextField();
        btnIncluirSala = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtRecebeSala = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Pauta:");

        jLabel2.setText("Ata:");

        jLabel3.setText("Tema:");

        jLabel4.setText("Nª Pessoas:");

        jLabel5.setText("Proprietario:");

        jLabel6.setText("Presença:");

        jLabel7.setText("Dia:");

        jLabel8.setText("Hora/Inicio:");

        jLabel9.setText("Hora/Fim:");

        jLabel10.setText("Sugestão de Local:");

        txtnPessoas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnPessoasActionPerformed(evt);
            }
        });

        tb_Reuniao_Coordenador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pauta", "Ata", "Tema", "Nª Participantes", "Proprietario", "Presença", "Dia", "Hora do Inicio", "Hora do Fim", "Sugestão de Local", "Sala"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_Reuniao_Coordenador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_Reuniao_CoordenadorMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tb_Reuniao_Coordenador);

        jLabel11.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel11.setText("Criar Reuniões");

        btnIncluir.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btnIncluir.setText("Incluir");
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });

        btnAlterar.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnVisualizarRelatorio.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btnVisualizarRelatorio.setText("Visualizar Relatorio");
        btnVisualizarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarRelatorioActionPerformed(evt);
            }
        });

        btnLimpar.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnVoltar.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnVisualizarReunioes.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btnVisualizarReunioes.setText("Visualizar Reuniões");
        btnVisualizarReunioes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarReunioesActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel12.setText("Cadastrar Sala");

        jLabel13.setText("Sala");

        btnIncluirSala.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btnIncluirSala.setText("Incluir Sala");
        btnIncluirSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirSalaActionPerformed(evt);
            }
        });

        jLabel14.setText("Sala:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCadSala, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnIncluirSala))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtAta)
                                        .addComponent(txtPauta, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtTema, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtnPessoas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                        .addComponent(txtProprietario, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtRecebeSala, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPresenca, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtSugestao, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtHora_Fim, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtHora_Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(69, 69, 69)))
                                .addGap(23, 23, 23))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11)
                                .addGap(270, 270, 270))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(btnVisualizarRelatorio)
                        .addGap(18, 18, 18)
                        .addComponent(btnVisualizarReunioes, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCadSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnIncluirSala))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txtPauta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtAta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtTema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtnPessoas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtProprietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtRecebeSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnIncluir)
                            .addComponent(btnAlterar)
                            .addComponent(btnExcluir)
                            .addComponent(btnVisualizarRelatorio)
                            .addComponent(btnLimpar)
                            .addComponent(btnVoltar)
                            .addComponent(btnVisualizarReunioes)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtPresenca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtHora_Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtHora_Fim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSugestao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnPessoasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnPessoasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnPessoasActionPerformed

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
        // TODO add your handling code here:
        
        validandoCadastro();//Invocando metdos
        add_Objeto_na_Lista();
    }//GEN-LAST:event_btnIncluirActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        excluirDados();//Invocando Metodos
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
        alterarDadosTb();//Invocando Metodos
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void tb_Reuniao_CoordenadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_Reuniao_CoordenadorMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tb_Reuniao_CoordenadorMouseClicked

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        
        //chamando a tla de menu do coordenador
        dispose();
        Menu_Coordenador mc = new Menu_Coordenador();
        mc.setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnVisualizarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarRelatorioActionPerformed
        // TODO add your handling code here:
        
        visualizarRelatorio();//Invocando Metodos
    }//GEN-LAST:event_btnVisualizarRelatorioActionPerformed

    private void btnVisualizarReunioesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarReunioesActionPerformed
        // TODO add your handling code here:
        
        visualizarReunioesP();//Invocando Metodos
        
    }//GEN-LAST:event_btnVisualizarReunioesActionPerformed

    private void btnIncluirSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirSalaActionPerformed
        // TODO add your handling code here:
        
        receberDadosValidandoSala();//Invocando Metodos
    }//GEN-LAST:event_btnIncluirSalaActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        
        limparDados();//Invocando Metodos
    }//GEN-LAST:event_btnLimparActionPerformed
    
    // valida cadastrado inserindo todos os campos de informação dentro da tabela linha por linha
    public void validandoCadastro(){
        
        recebendoInformacoes();
        
        if (crc.getPauta().equals("") && crc.getAta().equals("") && crc.getTema().equals("") && crc.getnP().equals("") && crc.getProprietario().equals("") && crc.getPresenca().equals("") && crc.getDia().equals("") && crc.getHora().equals("") && crc.getHoraFim().equals("") && crc.getSugestao().equals("") && crc.getSala().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha os Campos!");
        }
        else
           if (crc.getPauta().equals("") && crc.getAta() != "" && crc.getTema() != "" && crc.getnP()!= "" && crc.getProprietario() != "" && crc.getPresenca() != "" && crc.getDia() != "" && crc.getHora()!= "" && crc.getHoraFim() != "" && crc.getSugestao()!= "" && crc.getSala() != "") {
            JOptionPane.showMessageDialog(null, "Preencha a Pauta!");
        }
        else
           if (crc.getPauta() != "" && crc.getAta().equals("") && crc.getTema() != "" && crc.getnP()!= "" && crc.getProprietario() != "" && crc.getPresenca() != "" && crc.getDia() != "" && crc.getHora()!= "" && crc.getHoraFim() != "" && crc.getSugestao()!= "" && crc.getSala() != "") {
            JOptionPane.showMessageDialog(null, "Preencha a Ata!");
        }
        else
           if (crc.getPauta() != "" && crc.getAta() != "" && crc.getTema().equals("") && crc.getnP()!= "" && crc.getProprietario() != "" && crc.getPresenca() != "" && crc.getDia() != "" && crc.getHora()!= "" && crc.getHoraFim() != "" && crc.getSugestao()!= "" && crc.getSala() != "") {
            JOptionPane.showMessageDialog(null, "Preencha o Tema!");
        }
        else
           if (crc.getPauta() != "" && crc.getAta() != "" && crc.getTema() != "" && crc.getnP().equals("") && crc.getProprietario() != "" && crc.getPresenca() != "" && crc.getDia() != "" && crc.getHora()!= "" && crc.getHoraFim() != "" && crc.getSugestao()!= "" && crc.getSala() != "") {
            JOptionPane.showMessageDialog(null, "Preencha o Campo Numero de Participantes!");
        }
        else
           if (crc.getPauta() != "" && crc.getAta() != "" && crc.getTema() != "" && crc.getnP()!= "" && crc.getProprietario().equals("") && crc.getPresenca() != "" && crc.getDia() != "" && crc.getHora()!= "" && crc.getHoraFim() != "" && crc.getSugestao()!= "" && crc.getSala() != "") {
            JOptionPane.showMessageDialog(null, "Informe o Proprietario");
        }
        else
           if (crc.getPauta() != "" && crc.getAta() != "" && crc.getTema() != "" && crc.getnP()!= "" && crc.getProprietario() != "" && crc.getPresenca().equals("") && crc.getDia() != "" && crc.getHora()!= "" && crc.getHoraFim() != "" && crc.getSugestao()!= "" && crc.getSala() != "") {
            JOptionPane.showMessageDialog(null, "Campo Presença em Reunião esta vazio!");
        }
        else
           if (crc.getPauta() != "" && crc.getAta() != "" && crc.getTema() != "" && crc.getnP()!= "" && crc.getProprietario() != "" && crc.getPresenca() != "" && crc.getDia().equals("") && crc.getHora() != "" && crc.getHoraFim()!= "" && crc.getHoraFim() != "" && crc.getSugestao()!= "" && crc.getSala() != "") {
            JOptionPane.showMessageDialog(null, "Campo Dia esta vazio!");
        }
        else
           if (crc.getPauta() != "" && crc.getAta() != "" && crc.getTema() != "" && crc.getnP()!= "" && crc.getProprietario() != "" && crc.getPresenca() != "" && crc.getDia() != "" && crc.getHora().equals("")&& crc.getHoraFim() != "" && crc.getSugestao()!= "" && crc.getSala() != "") {
            JOptionPane.showMessageDialog(null, "Campo Hora do Inicio da Reunião esta vazio!");
        }
        else
           if (crc.getPauta() != "" && crc.getAta() != "" && crc.getTema() != "" && crc.getnP()!= "" && crc.getProprietario() != "" && crc.getPresenca() != "" && crc.getDia() != "" && crc.getHora()!= "" && crc.getHoraFim().equals("") && crc.getSugestao()!= "" && crc.getSala() != "") {
            JOptionPane.showMessageDialog(null, "Campo Horario do Fim da Reunião esta vazio!");
        }
        else
           if (crc.getPauta() != "" && crc.getAta() != "" && crc.getTema() != "" && crc.getnP()!= "" && crc.getProprietario() != "" && crc.getPresenca() != "" && crc.getDia() != "" && crc.getHora()!= "" && crc.getHoraFim() != "" && crc.getSugestao().equals("") && crc.getSala() != "") {
            JOptionPane.showMessageDialog(null, "Campo Sugestão de Local esta vazio!");
        }
        else
           if (crc.getPauta() != "" && crc.getAta() != "" && crc.getTema() != "" && crc.getnP()!= "" && crc.getProprietario() != "" && crc.getPresenca() != "" && crc.getDia() != "" && crc.getHora()!= "" && crc.getHoraFim() != "" && crc.getSugestao() != "" && crc.getSala().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo Sala esta vazio!");
        }
        else
           if (crc.getPauta() != "" && crc.getAta() != "" && crc.getTema() != "" && crc.getnP()!= "" && crc.getProprietario() != "" && crc.getPresenca() != "" && crc.getDia() != "" && crc.getHora()!= "" && crc.getHoraFim() != "" && crc.getSugestao()!= ""  && crc.getSala() != "") {
               
               DefaultTableModel modelo = (DefaultTableModel) tb_Reuniao_Coordenador.getModel();
               Object[] dados= {crc.getPauta(),crc.getAta(),crc.getTema(),crc.getnP(),
               crc.getProprietario(), crc.getPresenca(),crc.getDia(),
               crc.getnP(),crc.getHoraFim(),crc.getSugestao(),crc.getSala()};
               modelo.addRow(dados);
               JOptionPane.showMessageDialog(null, "Cadastro de Reunião Realizado com Sucesso!!");
        }
       
    }
    
    //Adicionando Objeto ao ArrayList
    public void add_Objeto_na_Lista(){
        
        recebendoInformacoes();
        listaR.add(crc);
    }
    
    // Exclui dados da tabela pela linha inserida atravez do modelo
    public void excluirDados(){
        
        if (tb_Reuniao_Coordenador.getSelectedRow() != -1) {
            DefaultTableModel modelo = (DefaultTableModel) tb_Reuniao_Coordenador.getModel();
            modelo.removeRow(tb_Reuniao_Coordenador.getSelectedRow());
        }
        else{
            JOptionPane.showMessageDialog(null, "Você precisa Selecionar para Excluir!");
        }
    }
    
    //Objeto da classe da recebendo informações dos Campos
    public void recebendoInformacoes(){
        
        crc.setPauta(txtPauta.getText());
        crc.setAta(txtAta.getText());
        crc.setTema(txtTema.getText());
        crc.setnP(txtnPessoas.getText());
        crc.setProprietario(txtProprietario.getText());
        crc.setPresenca(txtPresenca.getText());
        crc.setDia(txtDia.getText());
        crc.setHora(txtHora_Inicio.getText());
        crc.setHoraFim(txtHora_Fim.getText());
        crc.setSugestao(txtSugestao.getText());
        crc.setSala(txtRecebeSala.getText());
    }
    
    // valida a ação e altera de acordo com a condição estabelecida e seta um novo valor na linha da tabela
    
    public void alterarDadosTb(){
        
        recebendoInformacoes();
        
        if (crc.getPauta().equals("") && crc.getAta().equals("") && crc.getTema().equals("") && crc.getnP().equals("") && crc.getProprietario().equals("") && crc.getPresenca().equals("") && crc.getDia().equals("") && crc.getHora().equals("") && crc.getHoraFim().equals("") && crc.getSugestao().equals("") && crc.getSala().equals("")) {
            JOptionPane.showMessageDialog(null, "Adicione uma Reunião!");
        }
        if (crc.getPauta() != "" && crc.getAta() != "" && crc.getTema() != "" && crc.getnP()!= "" && crc.getProprietario().equals("sim") && crc.getPresenca() != "" && crc.getDia() != "" && crc.getHora()!= "" && crc.getHoraFim() != "" && crc.getSugestao()!= ""  && crc.getSala() != "") {
             
            tb_Reuniao_Coordenador.setValueAt(txtPauta.getText(), tb_Reuniao_Coordenador.getSelectedRow(),0);
            tb_Reuniao_Coordenador.setValueAt(txtAta.getText(), tb_Reuniao_Coordenador.getSelectedRow(),1);
            tb_Reuniao_Coordenador.setValueAt(txtTema.getText(), tb_Reuniao_Coordenador.getSelectedRow(),2);
            tb_Reuniao_Coordenador.setValueAt(txtnPessoas.getText(), tb_Reuniao_Coordenador.getSelectedRow(),3);
            tb_Reuniao_Coordenador.setValueAt(txtProprietario.getText(), tb_Reuniao_Coordenador.getSelectedRow(),4);
            tb_Reuniao_Coordenador.setValueAt(txtPresenca.getText(), tb_Reuniao_Coordenador.getSelectedRow(),5);
            tb_Reuniao_Coordenador.setValueAt(txtDia.getText(), tb_Reuniao_Coordenador.getSelectedRow(),6);
            tb_Reuniao_Coordenador.setValueAt(txtHora_Inicio.getText(), tb_Reuniao_Coordenador.getSelectedRow(),7);
            tb_Reuniao_Coordenador.setValueAt(txtHora_Fim.getText(), tb_Reuniao_Coordenador.getSelectedRow(),8);
            tb_Reuniao_Coordenador.setValueAt(txtSugestao.getText(), tb_Reuniao_Coordenador.getSelectedRow(),9);
            JOptionPane.showMessageDialog(null, "Campo Alterado com Sucesso!");
        }
        else{
           JOptionPane.showMessageDialog(null, "Você não e Proprietario!"); 
        }
    }
    
    // recebe o campo sala valida e envia para o cadastro de reunião
    public void receberDadosValidandoSala(){
     
        SalaR_Comum sala = new SalaR_Comum();
        sala.setNomeSala(txtCadSala.getText());
       
        if (sala.getNomeSala().equals("")) {
            JOptionPane.showMessageDialog(null," Campo Cadastro de Sala está vazio!");
        }
        else
          if (sala.getNomeSala().equals(txtRecebeSala.getText())) {
              JOptionPane.showMessageDialog(null, sala.getNomeSala()+" já esta Reservada!");
        }
        if (sala.getNomeSala() != "") {
            txtRecebeSala.setText(sala.getNomeSala());
        }
        txtCadSala.setText("");
       
    }
    
    //visualiza reunião caso o usuario confirme sua presença e se o objeto Visualizar for null
    // ele pega o ToString do Cadastro de Reunião
    public void visualizarReunioesP(){
        
         recebendoInformacoes();
       
        if (visualizar == null && crc.getPresenca().equals("sim")) {
            //dispose();
            visualizar = new Relatorio_Presença_Reunioes();
            visualizar.setVisible(true);
            visualizar.receberRelatorio(percorrendoObjeto());
        }
        if(crc.getPresenca().equals("não")){
            JOptionPane.showMessageDialog(null,"não Existe Nenhuma Reunião com Sua presença!");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario_CadR_Coordenador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario_CadR_Coordenador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario_CadR_Coordenador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario_CadR_Coordenador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario_CadR_Coordenador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JButton btnIncluirSala;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnVisualizarRelatorio;
    private javax.swing.JButton btnVisualizarReunioes;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tb_Reuniao_Coordenador;
    private javax.swing.JTextField txtAta;
    private javax.swing.JTextField txtCadSala;
    private javax.swing.JTextField txtDia;
    private javax.swing.JTextField txtHora_Fim;
    private javax.swing.JTextField txtHora_Inicio;
    private javax.swing.JTextField txtPauta;
    private javax.swing.JTextField txtPresenca;
    private javax.swing.JTextField txtProprietario;
    private javax.swing.JTextField txtRecebeSala;
    private javax.swing.JTextField txtSugestao;
    private javax.swing.JTextField txtTema;
    private javax.swing.JTextField txtnPessoas;
    // End of variables declaration//GEN-END:variables
}
